# Galaxy Selector MOC

**Compared to the "Simple Galaxy Selector, this works with Multi-Ordering-Sky-Maps**

**ASTROPY_HEALPIX NOT INSTALLED -> DOES NOT WORK ON NERSC**


***NOTE (this note may be wrong, just copied from old notebook)***: Before anything can happen, download the GW event localization map. Open the terminal and type:
"curl -O https://gracedb.ligo.org/api/superevents/sid/files/bayestar.fits,0"
with sid = superevent ID (could be incorporated into this notebook)

Select the galaxies to observe by WWFI in this simple manner:
- get the LIGO event data
- read the LIGO event data into the notebook, extract some information
- read the DESI database into the notebook, "clean" the data
- get the 90% credible regions for the event, add them as a column to the data
- only keep data within the 90% region
- calculate all the luminosities (& more)
- rank them by luminosity (for now just print the TARGETID), 3D/2D localization and with a luminosity-distance 2D dependant counterpart likelihood

Sources: 
- https://iopscience.iop.org/article/10.3847/0067-0049/226/1/10
- https://emfollow.docs.ligo.org/userguide/tutorial/skymaps.html
- https://emfollow.docs.ligo.org/userguide/tutorial/multiorder_skymaps.html
- https://arxiv.org/pdf/1710.05452.pdf

In [10]:
import numpy as np
from scipy.stats import norm
import scipy as sc

from astropy.io import fits
from astropy.table import Table, hstack
from astropy import table

import healpy as hp
import astropy_healpix as ah

from astropy.table import QTable

import psycopg2

from astropy.cosmology import Planck18, z_at_value
from astropy.coordinates import Distance 
from astropy import units as u

import astropy.constants as asc

import matplotlib.pyplot as plt

Specifiy the path where the data is located and then load the data (this loads everything, just have a look)

In [3]:
path = "/global/homes/j/jgassert/Code/data/bayestar.multiorderS200311bg.fits,1"
skymap = QTable.read(path)

skymap[:5]

<QTable length=5>
 UNIQ      PROBDENSITY       ...     DISTSIGMA             DISTNORM       
              1 / sr         ...        Mpc                1 / Mpc2       
int64        float64         ...      float64              float64        
----- ---------------------- ... ------------------ ----------------------
 1024  2.810789289065552e-31 ... 203.98712615523553  5.651336738354135e-06
 1025 2.2410403428136984e-31 ...                1.0                    0.0
 1026 2.0339165245847635e-30 ...  94.01334803516339  4.378865855578356e-06
 1027  1.742573180996848e-31 ...  584.6367464295139 5.9324972315106206e-05
 1028 5.0178196630906625e-30 ...                1.0                    0.0

### Get basic values from GW event

We now extract some basic information  from the healpix data:
- ipix_max: pixel with highest likelihood
- npix: total number of pixels
- ra, dec: ra and dec of the pixel with the highest likelihood

Then we open the full fits file and extract some more basic info from the header:
- dist_mean: mean distance of the GW event
- dist_std: error of the distance

In [4]:
# most probable sky location
i = np.argmax(skymap["PROBDENSITY"])
uniq = skymap[i]["UNIQ"]
print("UNIQ ID of highest prob sky localization: ", uniq)

UNIQ ID of highest prob sky localization:  8635874


In [5]:
# calculate the most probable pixel, convert to RA and dec
level_max, ipix_max = ah.uniq_to_level_ipix(uniq)
nside = ah.level_to_nside(level_max)
ra, dec = ah.healpix_to_lonlat(ipix_max, nside, order = "nested")
print("Highest probability at (RA, dec): ", ra.deg, dec.deg, "with prob [1/deg^2] of: ", skymap[i]['PROBDENSITY'].to_value(u.deg**-2))

Highest probability at (RA, dec):  1.8896484375000004 -6.955230191010185 with prob [1/deg^2] of:  0.04597608759643093


Now open the fits file and read basics info from the header

In [6]:
fits_gw = fits.open(path)
header = fits_gw[1].header
dist_mean = header["DISTMEAN"]
dist_std = header["DISTSTD"]
print("The dist_mean and dist_std values: ", dist_mean*u.Mpc, dist_std*u.Mpc)

The dist_mean and dist_std values:  924.038047662503 Mpc 188.4869314505396 Mpc


In [14]:
# these values (924, 188Mpc) are close to z= 0.19, 0.03

### Get DESI data

Establish a connection to the DESI database and load the daily data.

In [6]:
try:
    db = psycopg2.connect(host='decatdb.lbl.gov', database='desidb', user='desi', password = "5kFibers!", port="5432")
    cursor = db.cursor()
except (Exception, psycopg2.Error) as error:
    print(error)

cursor = db.cursor()

In [8]:
redux = 'daily'
query = 'SELECT f.targetid,f.target_ra,f.target_dec,c.tileid,c.night,r.z,r.zerr,r.zwarn,r.deltachi2,f.flux_z,f.bgs_target,f.ebv, f.sersic, f.mws_target, c.filename\n' \
                    f'FROM {redux}.tiles_fibermap f\n' \
                    f'INNER JOIN {redux}.cumulative_tiles c ON f.cumultile_id=c.id\n' \
                    f'INNER JOIN {redux}.tiles_redshifts r ON r.cumultile_id=c.id AND r.targetid=f.targetid\n' \
                    f'WHERE q3c_radial_query( f.target_ra, f.target_dec, {ra.deg}, {dec.deg}, 50);'

cursor.execute(query)
rows = cursor.fetchall()

## Do all the calculations, selections,...

- turn the daily DESI data into a Table
- do some basic data selection stuff: only keep good + positive redshifts, only positive values of z-band flux and eliminate duplicates (right now simply takes the first entry)
- add the ipix (healpix) pixel value for each target
- calculate the probability for each target
- calculate the probabilities for each object
- add these values to the able ("PROB"), select only targets within the 90% credible region (i.e. with a certainty of 90% the GW event is inside this region)
- calculate the distances and its errors from the redshift, add to the data table
- calculate the 3D probability just like here: https://iopscience.iop.org/article/10.3847/0067-0049/226/1/10 (§4) and add these values to the table
- sort the table by its 3D probability (descending)
- calculate absolute and apparent magnitude, luminosity and add to table

The final step is to include the calculation of the most likely host galaxy from https://arxiv.org/pdf/1710.05452.pdf (GW170817); these values are then also added to the table as "P_GAL"

In [199]:
if rows:
    data = Table(list(map(list, zip(*rows))),
                             names=['TARGETID', 'TARGET_RA', 'TARGET_DEC', 'TILEID', 'NIGHT', 'Z', 'ZERR', 'ZWARN', 'DELTACHI2', 'FLUX_Z', 'BGS_TARGET', 'EBV', 'SERSIC', 'MWS_TARGET','FILENAME'])
data[:5:-1] 

<Table length=14991129>
      TARGETID      ...
       int64        ...
------------------- ...
2305843041975433202 ...
2305843041975438825 ...
         -400209204 ...
         -400209218 ...
2305843041975432625 ...
2305843041975435467 ...
2305843041988016046 ...
2305843041975402913 ...
2305843041979612532 ...
2305843041967019488 ...
                ... ...
  39627914995566487 ...
  39627914995565773 ...
  39627908976739510 ...
  39627908976739147 ...
  39627908968350406 ...
            -739970 ...
            -739998 ...
            -740031 ...
            -740077 ...
            -740099 ...

basic data clean up:

In [200]:
data = data[data['ZWARN']==0]
data = data[data['Z']>=0]
data = data[data['FLUX_Z']>0]
data = table.unique(data, keys = "TARGETID")

calculate the healpix id for every object in the catalog and its probability; then append this data to the Table

In [201]:
max_level = 29 # highest possible HEALPix resolution that can be represented in a 64-bit signed integer
max_nside = ah.level_to_nside(max_level)
level, ipix = ah.uniq_to_level_ipix(skymap["UNIQ"])

In [202]:
level, len(level), ipix, len(ipix) 

(array([ 4,  4,  4, ..., 10, 10, 10]),
 19200,
 array([      0,       1,       2, ..., 4454033, 4454034, 4454035]),
 19200)

In [203]:
index = ipix*(2**(max_level-level))**2

In [204]:
index,len(index)

(array([                  0,    1125899906842624,    2251799813685248, ...,
        1224315268499505152, 1224315543377412096, 1224315818255319040]),
 19200)

In [205]:
sorter = np.argsort(index)

In [206]:
sorter, len(sorter)

(array([   0,    1,    2, ..., 2301, 2302, 2303]), 19200)

In [207]:
match_ipix = ah.lonlat_to_healpix(data["TARGET_RA"]*u.deg, data["TARGET_DEC"]*u.deg, max_nside, order='nested')


In [208]:
match_ipix

array([2728622294581067943, 2728621779287900438, 2728621850916985205, ...,
        727443823644003449,  727441492111965904,  727441547847715670])

In [209]:
i = sorter[np.searchsorted(index, match_ipix, side='right', sorter=sorter) - 1]

In [210]:
i, len(i)

(array([1939, 1939, 1939, ...,  645,  645,  645]), 6792308)

In [211]:
probs = skymap[i]['PROBDENSITY'].to_value(u.deg**-2)

In [212]:
probs, len(probs)

(array([5.71064285e-34, 5.71064285e-34, 5.71064285e-34, ...,
        7.17220113e-33, 7.17220113e-33, 7.17220113e-33]),
 6792308)

In [213]:
len(data)

6792308

In [214]:
#data = data.keep_columns(["TARGETID", "TARGET_RA", "TARGET_DEC", "TILEID", "NIGHT", "Z", "ZERR", "ZWARN", "DELTACHI2", "FLUX_Z", "BGS_TARGET", "EBV", "SERSIC", "MWS_TARGET", "FILENAME"])
                          

In [215]:
data = hstack([data, Table({"UNIQ": i}), Table({"PROB": probs})])

In [216]:
data[:5]

<Table length=5>
     TARGETID        TARGET_RA     ...  UNIQ          PROB        
      int64           float64      ... int64        float64       
----------------- ---------------- ... ----- ---------------------
39627126168619831 161.689448670564 ...  1939 5.710642848039233e-34
39627126168620535 161.722238626931 ...  1939 5.710642848039233e-34
39627126168621116 161.748119776018 ...  1939 5.710642848039233e-34
39627126168621739   161.7753477084 ...  1939 5.710642848039233e-34
39627126168622209 161.795718217228 ...  1939 5.710642848039233e-34

In [217]:
i[0]

1939

In [218]:
np.min(probs), np.max(probs)

(3.169267167263445e-39, 5.304415237478843e-30)

In [219]:
type(skymap)

astropy.table.table.QTable

In [220]:
skymap_sort = Table(skymap, copy = True)

In [221]:
# find the 90% credible region

skymap_sort.sort('PROBDENSITY', reverse=True)

In [222]:
skymap

<QTable length=19200>
  UNIQ       PROBDENSITY       ...     DISTSIGMA             DISTNORM       
                1 / sr         ...        Mpc                1 / Mpc2       
 int64         float64         ...      float64              float64        
------- ---------------------- ... ------------------ ----------------------
   1024  2.810789289065552e-31 ... 203.98712615523553  5.651336738354135e-06
   1025 2.2410403428136984e-31 ...                1.0                    0.0
   1026 2.0339165245847635e-30 ...  94.01334803516339  4.378865855578356e-06
   1027  1.742573180996848e-31 ...  584.6367464295139 5.9324972315106206e-05
   1028 5.0178196630906625e-30 ...                1.0                    0.0
   1029  4.797580236086145e-29 ... 1168.6465400854165  0.0026780709901027743
   1030 1.9570653020315176e-30 ...  648.5468293392516  3.554211921364464e-05
   1031 2.1886313614548153e-29 ...  580.2976827897337 1.9247360186695577e-05
   1032 4.7507186214818375e-30 ...  79.91169788411344 4.4634332358087994e-06
    ...                    ... ...                ...                    ...
8648290      66.65205919396716 ... 185.49761738883043 1.3280349168903653e-06
8648291      65.42537590216465 ... 186.14127017445352 1.3311678091484858e-06
8648324      66.61653987272027 ... 177.98398636145396 1.3048902111890403e-06
8648325      67.38801855914099 ... 178.48562529080766 1.3075506015415647e-06
8648326      64.22975188028938 ... 178.22491445599215  1.305189627368742e-06
8648327      65.12233606897505 ...  178.7212778738976 1.3078667420697282e-06
8648336      67.92192119647007 ...  179.0034957317144 1.3102506149175279e-06
8648337      65.95208793464863 ... 181.89229601179494 1.3162987977044667e-06
8648338       65.7877653263752 ...  179.2351345317829 1.3105874441479286e-06
8648339      66.21798679316638 ...  179.7652774899264 1.3133478141479834e-06

In [223]:
skymap_sort

<Table length=19200>
  UNIQ       PROBDENSITY       ...     DISTSIGMA             DISTNORM       
                1 / sr         ...        Mpc                1 / Mpc2       
 int64         float64         ...      float64              float64        
------- ---------------------- ... ------------------ ----------------------
8635874      150.9305923102596 ... 177.93280764677917 1.2849339652181568e-06
8635829     150.90015925644565 ... 177.80232609133046 1.2843604402415653e-06
8635881     150.81080736723487 ...  178.0667315631715 1.2855036372743902e-06
8635806      150.7196217659106 ... 177.67590777910323 1.2837893324140424e-06
8636263      150.6357713408702 ... 174.41913767344835 1.2756231847675179e-06
8636280     150.60578927581113 ...   174.582871711354 1.2762836212810563e-06
8635880      150.5516562424454 ... 177.40748819509628  1.282088669267722e-06
8635886     150.53933218598846 ...  178.2052621826929 1.2860770614342774e-06
8635883      150.5320859987755 ... 177.54694120991212  1.282689341386773e-06
    ...                    ... ...                ...                    ...
   3728   9.29375654984209e-38 ...                1.0                    0.0
   3732  7.162367665050586e-38 ...                1.0                    0.0
   3647  6.956581102684149e-38 ...                1.0                    0.0
   3641  6.901973916790275e-38 ... 1567.6723018998007  8.780519582593523e-08
   3644  6.640308514566586e-38 ...  1660.075768701239  9.650491817105248e-08
   3642  6.394829656300373e-38 ... 1969.0270330118285  1.361367971108613e-07
   3731  6.083456523662679e-38 ...                1.0                    0.0
   3643   4.04649038540755e-38 ... 1211.8402713241567   5.53253846812993e-08
   3646 3.9823348565345216e-38 ... 1436.5997884285189  6.428116361327975e-08
   3729   3.59724151867292e-38 ... 1359.2926245330314  5.899430725874264e-08

In [224]:
level, ipix = ah.uniq_to_level_ipix(skymap_sort['UNIQ'])
pixel_area = ah.nside_to_pixel_area(ah.level_to_nside(level))

In [225]:
prob = pixel_area * skymap_sort['PROBDENSITY']

In [226]:
cumprob = np.cumsum(prob)

In [227]:
i = cumprob.searchsorted(0.9)

In [228]:
i

7896

In [229]:
area_90 = pixel_area[:i].sum()
area_90.to_value(u.deg**2)

51.97063618706022

In [230]:
skymap_sort[:i]

<Table length=7896>
  UNIQ     PROBDENSITY     ...     DISTSIGMA             DISTNORM       
              1 / sr       ...        Mpc                1 / Mpc2       
 int64       float64       ...      float64              float64        
------- ------------------ ... ------------------ ----------------------
8635874  150.9305923102596 ... 177.93280764677917 1.2849339652181568e-06
8635829 150.90015925644565 ... 177.80232609133046 1.2843604402415653e-06
8635881 150.81080736723487 ...  178.0667315631715 1.2855036372743902e-06
8635806  150.7196217659106 ... 177.67590777910323 1.2837893324140424e-06
8636263  150.6357713408702 ... 174.41913767344835 1.2756231847675179e-06
8636280 150.60578927581113 ...   174.582871711354 1.2762836212810563e-06
8635880  150.5516562424454 ... 177.40748819509628  1.282088669267722e-06
8635886 150.53933218598846 ...  178.2052621826929 1.2860770614342774e-06
8635883  150.5320859987755 ... 177.54694120991212  1.282689341386773e-06
    ...                ... ...                ...                    ...
2149706 14.389172913885645 ... 171.27986061740634 1.2120790145520037e-06
 536904 14.373032712282104 ...  222.9655202150443 1.3770042220633078e-06
2152725 14.372958631858179 ... 260.83502630628317 1.7748455082053907e-06
 537603 14.351342701305397 ... 286.96144145237747 2.1771032814581472e-06
 551555 14.298468794776062 ...  220.3202409824387 1.5062624858907812e-06
 536898 14.279300759887022 ...  229.7343209162045 1.4113149337938014e-06
 536906 14.269563326813111 ... 216.40034793358873 1.3468108022571136e-06
2159398 14.260370031980896 ... 155.48853063672757 1.2255092429606125e-06
 539898 14.225536432282727 ... 157.15101912081803 1.2349098544781808e-06
2161989  14.22360965592587 ... 211.73694376847772 1.4033039005733966e-06

In [240]:
mask = [data["UNIQ"][q] in skymap_sort["UNIQ"][:i] for q in range(len(data))]

In [239]:
len(data)

6792308

In [246]:
np.max(data["UNIQ"]), np.min(skymap_sort["UNIQ"])

(2268, 1024)

In [248]:
1024 in data["UNIQ"]

False

In [241]:
data_90 = data[mask]

In [242]:
data_90[:5]

<Table length=0>
TARGETID TARGET_RA TARGET_DEC TILEID NIGHT ... MWS_TARGET FILENAME  UNIQ   PROB 
 int64    float64   float64   int64  int64 ...   int64     str71   int64 float64
-------- --------- ---------- ------ ----- ... ---------- -------- ----- -------

In [243]:
distances = Distance(z=prob_data["Z"], cosmology=Planck18)
distances_err = Distance(z=prob_data["ZERR"], cosmology=Planck18)

NameError: name 'prob_data' is not defined

In [ ]:
dP_dV = data_90["IPIX"]*distnorm[data_90["IPIX"]]*norm(distmu[data_90["IPIX"]], distsigma[data_90["IPIX"]]).pdf(distances)/pixarea